"""Pure-Python CAD core: document, sketches, mesh kernel."""

from cadcore.document import Document, Feature, FeatureType
from cadcore.mesh import (
    BooleanOp,
    Mesh,
    boolean_op,
    extrude_circle,
    extrude_filleted_profile,
    extrude_pocketed_filleted_profile,
    extrude_pocketed_profile,
    extrude_profile,
    extrude_rectangle,
    fillet_profile,
    profile_with_hole,
    make_box,
    make_cylinder,
    make_sphere,
    read_stl_binary,
    revolve_circle,
    revolve_profile,
    revolve_rectangle,
    write_stl,
    write_stl_binary,
)
from cadcore.sketch import CircleEntity, LineEntity, PlaneFrame, RectEntity, Sketch

__all__ = [
    "Document",
    "Feature",
    "FeatureType",
    "Mesh",
    "BooleanOp",
    "boolean_op",
    "make_box",
    "make_sphere",
    "make_cylinder",
    "extrude_profile",
    "extrude_rectangle",
    "extrude_circle",
    "fillet_profile",
    "extrude_filleted_profile",
    "profile_with_hole",
    "extrude_pocketed_profile",
    "extrude_pocketed_filleted_profile",
    "revolve_profile",
    "revolve_rectangle",
    "revolve_circle",
    "write_stl",
    "write_stl_binary",
    "read_stl_binary",
    "Sketch",
    "PlaneFrame",
    "LineEntity",
    "RectEntity",
    "CircleEntity",
]
